server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: ecommerce-gateway
  cloud:
    gateway:
      routes:
        - id: ecommerce
          uri: lb://ecommerce-service
          #http://localhost:8082/
          predicates:
            - Path=/ecommerce/**
        - id: fundtransfer
          uri: lb://fundtransfer-service
          #http://localhost:8081/
          predicates:
            - Path=/fundtransfer/**